### ISSUE TITLE
Wrong texts of the query page.

### ISSUE THREAD

**Issue by liuchangshiye** [COOL-cohort/COOL-webapp#3]
The query page displays "Cohort", "Show Cohorts", "Here list all generated cohorts" and "Cohort > show Cohorts", which is the same as the cohort page and not consistent with the Query.

**Comment by KimballCai** [comment]
solve this issue in the commit  [2f79252](https://github.com/COOL-cohort/COOL-webapp/commit/2f79252e63375d828768031eb0fa5894953d1727)
